# Site Information
site_name: Fluid Numerics Journal
site_author: Fluid Numerics
site_dir: public
site_url: ""
repo_name: GitHub/fluidnumerics/journal.fluidnumerics.com
repo_url: https://github.com/fluidnumerics/journal.fluidnumerics.com
edit_uri: edit/master/docs

# Directory where site content is located
docs_dir: docs

# Site navigation 
nav:
  - Home: README.md
  - Blog Posts:
    - Port, Optimize, and Scale on AMD Instinct GPUs:  port-optimize-and-scale-with-hostaisle/README.md
    - Saving Energy in Quantum Chromodynamics Simulations: saving-energy-on-quantum-chromodynamics-simulations/README.md
    - Accelerating Science with GPU software optimization: accelerating-science-with-optimization/README.md
    - What is a mentored sprint: what-is-a-mentored-sprint/README.md
    - Fine Tuning LLAMA 3 on AMD GPUs: fine-tuning-llama-3/README.md
    - Getting started with LLAMA3 on AMD GPUs: getting-started-with-llama3/README.md
    - HIP performance comparisons- AMD and Nvidia GPUs: hip-performance-comparisons-amd-and-nvidia-gpus/README.md
  #- Working with hipBlas in Fortran: working-with-hipblas-in-fortran/README.md
  - Mentored Sprint Reports:
    - EmPrism (Quantum Chromodynamics) : emprism-mentored-sprint-report/README.md
    - EXESS (Quantum Chemistry) : exess-mentored-sprint-report/README.md



theme: 
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  features:
    - navigation.footer
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
         
    - scheme: default 
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins: []

copyright: Copyright &copy; 2017 - 2024 Fluid Numerics LLC
extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@FluidNumerics
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/FluidNumerics/
    - icon: fontawesome/brands/github
      link: https://github.com/fluidnumerics
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/fluidnumerics
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/fluidnumerics/
